[build-system]
requires = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
requires-python = ">=3.8"

[tool.black]
line-length = 110

[tool.mypy]
files = ["."]
strict_optional = false
allow_redefinition = true
show_error_context = false
show_column_numbers = true
